@startuml activity_diagram
start
:Инициализация игры;
repeat
  :Ожидание хода игрока;
  if (Ход валиден?) then (да)
    :Выполнить ход;
    :Проверить состояние игры;
    if (Игра продолжается?) then (да)
      :Ход ИИ;
      :Обновить доску;
    else (нет)
      :Завершить игру;
    endif
  else (нет)
    :Сообщить об ошибке;
  endif
repeat while (Игра продолжается?) is (да)
stop
@enduml