@startuml use_case_diagram
left to right direction
actor Игрок as Player

rectangle Игра {
  (Начать) as play
  (Загрузить) as load
  (Сохранить) as save
  (Начать заново) as restart
  (Выйти) as exit
  
  Player --> play
  Player --> load
  Player --> save
  Player --> restart
  Player --> exit
}
@enduml